/* DO NOT EDIT THIS FILE
 * - common_functions.h (ZUON)
 * - Copyright: Prof. Kevin Andrea, George Mason University.  All Rights Reserved
 * - Date: Aug 2022
 */
#ifndef COMMON_FUNCTIONS_H
#define COMMON_FUNCTIONS_H

#include "kifp.h"
#include "common_definitions.h"

#define IS_INTERACTIVE isatty(0)

#define ECHOTTY(str, ...) do {     \
  !IS_INTERACTIVE?printf("%s", YELLOW):1;       \
  !IS_INTERACTIVE?printf(str, ##__VA_ARGS__):1;   \
  !IS_INTERACTIVE?printf("%s", RST):1;          \
} while(0)

#define ECHONOTTY(str, ...) do {     \
  IS_INTERACTIVE?printf(str, ##__VA_ARGS__):1;   \
} while(0)


void print_prompt(char *msg);
void print_num(char *var, struct number_struct *num, int precision, int result);
void print_sym_not_found(char *str);
void disable_buffering(FILE *stream);
void enable_buffering(FILE *stream);
int fraction_to_binary(int fraction_part, int precision);
int binary_to_fraction(int binary, int *precision);
void print_binary_value(const char *msg, int whole, int fraction);
void print_value(const char *msg, kifp_t value);
void print_ni(char *msg);
void print_binary_whole(int val);
void print_binary_fraction(int val);

#endif
