/* DO NOT EDIT THIS FILE
 * - common_structs.h (ZUON)
 * - Copyright: Prof. Kevin Andrea, George Mason University.  All Rights Reserved
 * - Date: Aug 2022
 */

#ifndef COMMON_STRUCTS_H
#define COMMON_STRUCTS_H

typedef struct number_struct {
  char original[255];   // Reference String for Original User Input
  int is_negative;      // 1 if Negative, 0 if Positive        (eg. 3.25, whole = 3, is_negative = 0)
                        //                                     (eg.-3.25, whole = 3, is_negative = 1)
  int is_infinity;      // 1 if Infinity, 0 Otherwise  
  int is_nan;           // 1 if NaN, 0 Otherwise
  int whole;            // Whole Portion of Number             (eg. 3.25, whole = 3) 
  int fraction;         // 32-bit Fraction Portion in Binary   (eg. 3.25, frac  = 0x40000000)
  int precision;        // Used Internally, Ignore this Field
} Number_t;

#endif
